services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8443:443"
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 5s

networks:
  inception:
    driver: bridge

volumes:  # ✅ Ajout des volumes ici
  mariadb:
  wordpress:
